import Mathlib

/-!
# Challenge: headline theorems of the quantum Pauli basis test

Self-contained comparator challenge for the four registered QPBT headline
theorems: low-degree soundness, completeness of the Pauli basis test, its
soundness theorem, and the qubit-coordinate soundness corollary.

The challenge is **Mathlib-only**: apart from Mathlib it imports nothing but
its own modules under `Challenge/`, one for each library module that
contributes to the closure.  Together they re-declare, verbatim and in
dependency order, every definition in the transitive closure of the statements
of the four theorems; the theorems themselves are stated here with `sorry`.
Those modules and their imports mirror the library's own module partition
and import graph.  That is not cosmetic: Lean caches a nested proof and
a `match` auxiliary *per module*, names it after the first declaration of that
module that needs it, and lets a declaration see only the instances its
module's imports bring into scope, while the comparator compares the full
`ConstantInfo` of every closure constant, values and proofs included.  A
single-file challenge therefore cannot reproduce those names whenever the
library needs the same fact in two modules; the mirrored partition reproduces
them by construction.

The set of challenge modules is the entire human audit surface: a reader who
agrees that they state the intended theorems does not need to read anything
else.  The
[comparator](https://github.com/leanprover/comparator) tool verifies
mechanically that the [MIPStarRE](https://github.com/LionSR/MIPStarRE)
library declares statements identical to these and proves the theorems using
no axioms beyond `propext`, `Quot.sound`, and `Classical.choice`.

Each declaration carries a provenance comment (`-- source: <file>:<lines>`)
pointing at its origin in the MIPStarRE library, where docstrings cite the
paper passages being encoded, and each challenge module names the library
module it mirrors.  These files are generated by
`scripts/comparator/` in that repository; see the README alongside this file
for how to run the verification.
-/

open scoped BigOperators MatrixOrder Matrix ComplexOrder
