module

public import MIPStarRE.QPBT.Observables.WinImplications.MagicSquare

/-!
# Exact consistency winning implication

This module proves the exact same-question consistency bound for the two
players' Pauli-test measurements.

## References

The strategy consistency theorem proves item 1
of `lem:qld-win-implications`
from `references/qpbt-paper/14_analysis_of_the_pauli_basis_test.tex:192-267`
and blueprint `lem:qld-win-implications` and `lem:qld-win-implications-obs`.
-/

@[expose] public section

open scoped BigOperators Matrix ComplexOrder

namespace MIPStarRE.QPBT

open MIPStarRE.LDT hiding Measurement
open MIPStarRE.Quantum

noncomputable section

namespace WinImplications

/-- The self-loop verifier edge at one Pauli question type. This is the edge
used for item 1 of `lem:qld-win-implications`, paper
`14_analysis_of_the_pauli_basis_test.tex:197-199`. -/
def pauliLoopEdge (t : PauliType) : PauliEdge :=
  ⟨(t, t), by simp [pauliEdges]⟩

/-- Answer-mismatch mass at the first question generated by one sampler edge. -/
private noncomputable def firstQuestionMismatch {P : AdmissibleParams} {ε : ℝ}
    (S : ProjectiveSetting P ε) (e : PauliEdge) (z : PauliSpace P) : ℝ :=
  outcomeEventWeight S.toStrategy
    (e.1.1, pauliCL P e.1.1 z) (e.1.1, pauliCL P e.1.1 z)
    (fun A B => A ≠ B)

/-- Unequal answers to the same sampled question are rejected on its self-loop.
This is the rejection event used for item 1 of `lem:qld-win-implications`, paper
`14_analysis_of_the_pauli_basis_test.tex:197-199`. -/
theorem loopMismatch_le_rejection {P : AdmissibleParams} {ε : ℝ}
    (S : ProjectiveSetting P ε) (t : PauliType) (z : PauliSpace P) :
    outcomeEventWeight S.toStrategy
        (t, pauliCL P t z) (t, pauliCL P t z) (fun A B => A ≠ B) ≤
      pauliRejectionAt S.toStrategy (pauliLoopEdge t) z := by
  unfold pauliRejectionAt pauliSourceQuestions pauliLoopEdge
  dsimp
  apply outcome_event_weight_mono
  intro A B hne
  simp only [pauliWinPredicate, Bool.and_eq_true, ↓reduceIte,
    Bool.if_false_right, Bool.decide_and, Bool.decide_eq_true,
    Bool.and_eq_false_imp, decide_eq_false_iff_not, and_imp]
  intro _ _
  exact hne

/-- Strategy consistency is the same-question answer-mismatch probability. -/
private theorem strategyConsistency_eq_mismatch {P : AdmissibleParams} {ε : ℝ}
    (S : ProjectiveSetting P ε) :
    consistencyDefect (pauliQuestionMarginal P)
        (fun question a => heteroKron
          ((S.strategyMeasurement .alice question).effect a) 1)
        (fun question a => heteroKron 1
          ((S.strategyMeasurement .bob question).effect a))
        S.toStrategy.ψ =
      avgOver (pauliQuestionMarginal P) (fun question =>
        outcomeEventWeight S.toStrategy question question (fun A B => A ≠ B)) := by
  change consistencyDefect (pauliQuestionMarginal P)
      (fun question a => heteroKron ((S.toStrategy.A question).effect a)
        (1 : Op S.toStrategy.ιB))
      (fun question a => heteroKron (1 : Op S.toStrategy.ιA)
        ((S.toStrategy.B question).effect a))
      S.toStrategy.ψ = _
  unfold consistencyDefect outcomeEventWeight
  apply avgOver_congr
  intro question
  simp only [DistanceCalculus.consistency_term_eq_stateQForm]
  simp_rw [DistanceCalculus.placed_product_stateQForm_eq]
  apply Finset.sum_congr rfl
  intro A _
  apply Finset.sum_congr rfl
  intro B _
  by_cases hAB : A = B
  · simp [hAB]
  · simp [hAB, DistanceCalculus.stateQForm, outcomeWeight,
      applyOperatorToState]

/-- The consistency subtest bounds the off-diagonal defect of the two strategy
measurement families. This is item 1 of `lem:qld-win-implications`, paper
`14_analysis_of_the_pauli_basis_test.tex:197-199`, blueprint
`lem:qld-win-implications`. -/
theorem win_cons :
    ∃ C : ℝ, 1 ≤ C ∧
      ∀ (P : AdmissibleParams) (ε : ℝ) (S : ProjectiveSetting P ε),
      0 ≤ ε →
      consistencyDefect (pauliQuestionMarginal P)
        (fun question a => heteroKron
          ((S.strategyMeasurement .alice question).effect a) 1)
        (fun question a => heteroKron 1
          ((S.strategyMeasurement .bob question).effect a))
        S.toStrategy.ψ ≤ C * ε := by
  refine ⟨(Fintype.card PauliEdge : ℝ), ?_, ?_⟩
  · exact_mod_cast (Fintype.card_pos : 0 < Fintype.card PauliEdge)
  intro P ε S _
  rw [strategyConsistency_eq_mismatch]
  unfold pauliQuestionMarginal pauliQuestionDistribution
  rw [Distribution.avgOver_map, Distribution.avgOver_map]
  change avgOver (uniformDistribution (PauliEdge × PauliSpace P))
      (fun ez => firstQuestionMismatch S ez.1 ez.2) ≤ _
  rw [avgOver_uniform_prod]
  calc
    avgOver (uniformDistribution PauliEdge) (fun e =>
        avgOver (uniformDistribution (PauliSpace P)) (fun z =>
          firstQuestionMismatch S e z)) ≤
      avgOver (uniformDistribution PauliEdge)
        (fun _ => (Fintype.card PauliEdge : ℝ) * ε) := by
      apply avgOver_mono
      intro e
      calc
        _ ≤ avgOver (uniformDistribution (PauliSpace P))
            (pauliRejectionAt S.toStrategy (pauliLoopEdge e.1.1)) := by
          apply avgOver_mono
          intro z
          exact loopMismatch_le_rejection S e.1.1 z
        _ ≤ (Fintype.card PauliEdge : ℝ) * ε :=
          fixedEdgeRejection_le_error S _
    _ = (Fintype.card PauliEdge : ℝ) * ε := by
      exact avgOver_const_of_isProbability _
        (uniformDistribution_isProbability PauliEdge) _


end WinImplications

end

end MIPStarRE.QPBT
