module

public import Mathlib
public import Challenge.MIPStarRE.LDT.Basic.ParametersBase
public import Challenge.MIPStarRE.LDT.Preliminaries.Polynomials
public import Challenge.MIPStarRE.QPBT.Algebra.Coefficients
public import Challenge.MIPStarRE.QPBT.Algebra.Subspaces
public import Challenge.MIPStarRE.Quantum.FiniteMatrix.Basic
public import Challenge.MIPStarRE.QPBT.Algebra.FieldBasis
public import Challenge.MIPStarRE.QPBT.Algebra.LowDegreeCode
public import Challenge.MIPStarRE.QPBT.State
public import Challenge.MIPStarRE.Quantum.FiniteMatrix.NormalizedTrace
public import Challenge.MIPStarRE.QPBT.Algebra.Lines
public import Challenge.MIPStarRE.QPBT.Algebra.Pauli
public import Challenge.MIPStarRE.QPBT.Algebra.SelfDualBasis
public import Challenge.MIPStarRE.Quantum.Measurement
public import Challenge.MIPStarRE.QPBT.Algebra.SelfDualBasisTheorems
public import Challenge.MIPStarRE.LDT.Basic.Distribution
public import Challenge.MIPStarRE.QPBT.Algebra.PauliTheorems
public import Challenge.MIPStarRE.QPBT.Games.Defs
public import Challenge.MIPStarRE.QPBT.Games.DistributionAux
public import Challenge.MIPStarRE.QPBT.Games.CondLinear
public import Challenge.MIPStarRE.QPBT.Games.Consistency
public import Challenge.MIPStarRE.QPBT.Test.LowDegreeGame
public import Challenge.MIPStarRE.QPBT.Test.MagicSquare
public import Challenge.MIPStarRE.QPBT.Games.TypedCondLinear
public import Challenge.MIPStarRE.QPBT.Test.PauliBasisTest
public import Challenge.MIPStarRE.QPBT.Test.SoundnessDefs
public import Challenge.MIPStarRE.QPBT.Games.StrategyClasses
public import Challenge.MIPStarRE.QPBT.Test.LowDegreeGameMeasurements
public import Challenge.MIPStarRE.QPBT.Observables.WinImplications.Setup
public import Challenge.MIPStarRE.QPBT.Test.Completeness
public import Challenge.MIPStarRE.QPBT.Test.QubitForm

/-!
# Challenge: headline theorems of the quantum Pauli basis test

Self-contained comparator challenge for the four registered QPBT headline
theorems: low-degree soundness, completeness of the Pauli basis test, its
soundness theorem, and the qubit-coordinate soundness corollary.

The challenge is **Mathlib-only**: apart from Mathlib it imports nothing but
its own modules under `Challenge/`, one for each library module that
contributes to the closure.  Together they re-declare, verbatim and in
dependency order, every definition in the transitive closure of the statements
of the four theorems; the theorems themselves are stated here with `sorry`.
Those modules and their imports mirror the library's own module partition
and import graph.  That is not cosmetic: Lean caches a nested proof and
a `match` auxiliary *per module*, names it after the first declaration of that
module that needs it, and lets a declaration see only the instances its
module's imports bring into scope, while the comparator compares the full
`ConstantInfo` of every closure constant, values and proofs included.  A
single-file challenge therefore cannot reproduce those names whenever the
library needs the same fact in two modules; the mirrored partition reproduces
them by construction.

The set of challenge modules is the entire human audit surface: a reader who
agrees that they state the intended theorems does not need to read anything
else.  The
[comparator](https://github.com/leanprover/comparator) tool verifies
mechanically that the [MIPStarRE](https://github.com/LionSR/MIPStarRE)
library declares statements identical to these and proves the theorems using
no axioms beyond `propext`, `Quot.sound`, and `Classical.choice`.

Each declaration carries a provenance comment (`-- source: <file>:<lines>`)
pointing at its origin in the MIPStarRE library, where docstrings cite the
paper passages being encoded, and each challenge module names the library
module it mirrors.  These files are generated by
`scripts/comparator/` in that repository; see the README alongside this file
for how to run the verification.
-/

open scoped BigOperators MatrixOrder Matrix ComplexOrder
@[expose] public section

-- Compiler-generated declarations in the closure (no source
-- range); they regenerate identically during elaboration:
--   MIPStarRE.QPBT.MsType.ctorIdx  (from MIPStarRE/QPBT/Test/MagicSquare.lean)
--   _private.MIPStarRE.QPBT.Games.DistributionAux.0.MIPStarRE.QPBT.bind_uniformOnFinset_map._simp_1_3  (from MIPStarRE/QPBT/Games/DistributionAux.lean)
--   MIPStarRE.QPBT.PauliType.ctorElimType  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.PauliAnswer.ctorIdx  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.prefixRank.eq_1  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)
--   MIPStarRE.QPBT.PauliKind.ofNat_ctorIdx  (from MIPStarRE/QPBT/Algebra/Pauli.lean)
--   MIPStarRE.QPBT.PauliType.proxyTypeEquiv  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   _private.MIPStarRE.QPBT.Games.DistributionAux.0.MIPStarRE.QPBT.Distribution.map_map._simp_1_1  (from MIPStarRE/QPBT/Games/DistributionAux.lean)
--   MIPStarRE.QPBT.LdType.ofNat_ctorIdx  (from MIPStarRE/QPBT/Test/LowDegreeGame.lean)
--   _private.MIPStarRE.QPBT.Algebra.FieldBasis.0.MIPStarRE.QPBT.exists_fixed_field_model  (from [anonymous].lean)
--   _private.MIPStarRE.QPBT.Algebra.FieldBasis.0.MIPStarRE.QPBT.exists_self_dual_normal_basis_gal  (from [anonymous].lean)
--   _private.MIPStarRE.QPBT.Algebra.FieldBasis.0.MIPStarRE.QPBT.exists_selfDualNormalBasis  (from [anonymous].lean)
--   _private.MIPStarRE.QPBT.Games.DistributionAux.0.MIPStarRE.QPBT.bind_uniformOnFinset_map._simp_1_4  (from MIPStarRE/QPBT/Games/DistributionAux.lean)
--   _private.MIPStarRE.QPBT.Algebra.Subspaces.0.MIPStarRE.QPBT.isCompl_registerSubmodule_canonicalComplement  (from [anonymous].lean)
--   MIPStarRE.QPBT.instInhabitedMsType.default  (from MIPStarRE/QPBT/Test/MagicSquare.lean)
--   _private.MIPStarRE.QPBT.Algebra.Subspaces.0.MIPStarRE.QPBT.coordinate_eq_zero_of_prefixRank_eq  (from [anonymous].lean)
--   _private.MIPStarRE.QPBT.Algebra.FieldBasis.0.MIPStarRE.QPBT.exists_self_dual_normal_basis_gal._simp_1_2  (from MIPStarRE/QPBT/Algebra/FieldBasis.lean)
--   MIPStarRE.QPBT.PauliKind.ofNat  (from MIPStarRE/QPBT/Algebra/Pauli.lean)
--   _private.MIPStarRE.QPBT.Algebra.Subspaces.0.MIPStarRE.QPBT.isCompl_registerSubmodule_canonicalComplement._simp_1_4  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)
--   MIPStarRE.QPBT.MsAnswer.ctorIdx  (from MIPStarRE/QPBT/Test/MagicSquare.lean)
--   _private.MIPStarRE.QPBT.Games.DistributionAux.0.MIPStarRE.QPBT.bind_uniformOnFinset_map._simp_1_1  (from MIPStarRE/QPBT/Games/DistributionAux.lean)
--   _private.MIPStarRE.QPBT.Test.MagicSquare.0.MIPStarRE.QPBT.msConstraintVars  (from [anonymous].lean)
--   _private.MIPStarRE.QPBT.Algebra.FieldBasis.0.MIPStarRE.QPBT.trace_group_algebra_pairing._simp_1_2  (from MIPStarRE/QPBT/Algebra/FieldBasis.lean)
--   MIPStarRE.LDT.Distribution.mk.congr_simp  (from MIPStarRE/LDT/Basic/Distribution.lean)
--   MIPStarRE.QPBT.PauliType.ctorIdx  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   _private.MIPStarRE.QPBT.Games.DistributionAux.0.MIPStarRE.QPBT.bind_uniformOnFinset_map._simp_1_2  (from MIPStarRE/QPBT/Games/DistributionAux.lean)
--   MIPStarRE.QPBT.PauliType.point.inj  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.PauliAnswer.ctorElimType  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.PauliType.point.injEq  (from MIPStarRE/QPBT/Test/PauliBasisTest.lean)
--   MIPStarRE.QPBT.LdAnswer.ctorIdx  (from MIPStarRE/QPBT/Test/LowDegreeGame.lean)
--   _private.MIPStarRE.QPBT.Algebra.Subspaces.0.MIPStarRE.QPBT.registerSubmodule_eq_spanSubset._simp_1_2  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)
--   MIPStarRE.QPBT.instInhabitedLdType.default  (from MIPStarRE/QPBT/Test/LowDegreeGame.lean)
--   _private.MIPStarRE.QPBT.Algebra.Subspaces.0.MIPStarRE.QPBT.isCompl_registerSubmodule_canonicalComplement._simp_1_5  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)
--   MIPStarRE.QPBT.LdType.ofNat  (from MIPStarRE/QPBT/Test/LowDegreeGame.lean)
--   MIPStarRE.QPBT.LdAnswer.ctorElimType  (from MIPStarRE/QPBT/Test/LowDegreeGame.lean)
--   _private.MIPStarRE.QPBT.Algebra.Subspaces.0.MIPStarRE.QPBT.isCompl_registerSubmodule_canonicalComplement._simp_1_6  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)
--   MIPStarRE.QPBT.MsType.proxyTypeEquiv  (from MIPStarRE/QPBT/Test/MagicSquare.lean)
--   MIPStarRE.QPBT.registerSubmodule.eq_1  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)
--   MIPStarRE.QPBT.clDistribution.eq_1  (from MIPStarRE/QPBT/Games/CondLinearTheorems.lean)
--   MIPStarRE.QPBT.instInhabitedPauliKind.default  (from MIPStarRE/QPBT/Algebra/Pauli.lean)
--   MIPStarRE.QPBT.canonicalComplement.eq_1  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)
--   _private.MIPStarRE.QPBT.Algebra.FieldBasis.0.MIPStarRE.QPBT.normal_basis_trace_dual_apply._simp_1_2  (from MIPStarRE/QPBT/Algebra/FieldBasis.lean)
--   MIPStarRE.QPBT.PauliKind.ctorIdx  (from MIPStarRE/QPBT/Algebra/Pauli.lean)
--   _private.MIPStarRE.QPBT.Algebra.FieldBasis.0.MIPStarRE.QPBT.normal_basis_trace_dual_apply._simp_1_3  (from MIPStarRE/QPBT/Algebra/FieldBasis.lean)
--   MIPStarRE.QPBT.LdType.ctorIdx  (from MIPStarRE/QPBT/Test/LowDegreeGame.lean)
--   _private.MIPStarRE.QPBT.Algebra.Subspaces.0.MIPStarRE.QPBT.isCompl_registerSubmodule_canonicalComplement._simp_1_3  (from MIPStarRE/QPBT/Algebra/Subspaces.lean)

namespace MIPStarRE.QPBT

open MIPStarRE.LDT MIPStarRE.Quantum
open MIPStarRE.LDT.Preliminaries

-- source: MIPStarRE/QPBT/Test/Completeness.lean:263-268
--   (MIPStarRE.QPBT.exists_spcc_value_one)
/-- `lem:pauli-completeness`: every admissible Pauli basis test has a
value-one SPCC strategy. Blueprint `lem:pauli-completeness`, paper
`08_classical_and_quantum_low_degree_tests.tex:1229-1421`. -/
theorem exists_spcc_value_one (P : AdmissibleParams) :
    ∃ S : SymmetricStrategy (pauliBasisTestSymm P),
      S.IsSPCC ∧ S.toStrategy.value = 1 := by
  sorry

-- source: MIPStarRE/QPBT/Test/LowDegreeGameTheorems.lean:82-108
--   (MIPStarRE.QPBT.exists_ld_soundness)
/-- Quantum soundness of the simultaneous classical low individual degree test.
Blueprint `lem:ld-soundness`, paper
`references/qpbt-paper/08_classical_and_quantum_low_degree_tests.tex:413-458`. -/
theorem exists_ld_soundness :
    ∃ a b : ℝ, 1 ≤ a ∧ 0 < b ∧ b ≤ 1 ∧
      ∀ (L : LdParams) (ε : ℝ), 0 < ε →
        ∀ S : Strategy (ldGame L), S.IsProjective → 1 - ε ≤ S.value →
          ∃ GA : PolyMeasTuple L S.ιA, ∃ GB : PolyMeasTuple L S.ιB,
            consistencyDefect (uniformDistribution (Fin L.m → ScalarQ L))
                (fun u outcome =>
                  heteroKron
                    (((S.A (ldPointQuestionOf L u)).postprocess
                      (ldPointValuesOrZero L)).effect outcome) 1)
                (fun u outcome =>
                  heteroKron 1
                    ((GB.postprocess (evalPolyTupleAt u)).effect outcome))
                S.ψ ≤ deltaLd a b ε L.q L.m L.d L.k ∧
            consistencyDefect (uniformDistribution (Fin L.m → ScalarQ L))
                (fun u outcome =>
                  heteroKron
                    ((GA.postprocess (evalPolyTupleAt u)).effect outcome) 1)
                (fun u outcome =>
                  heteroKron 1
                    (((S.B (ldPointQuestionOf L u)).postprocess
                      (ldPointValuesOrZero L)).effect outcome))
                S.ψ ≤ deltaLd a b ε L.q L.m L.d L.k ∧
            consistencyDefect (uniformDistribution Unit)
                (fun _ g => heteroKron (GA.effect g) 1)
                (fun _ g => heteroKron 1 (GB.effect g))
                S.ψ ≤ deltaLd a b ε L.q L.m L.d L.k := by
  sorry

-- source: MIPStarRE/QPBT/Test/Soundness.lean:40-65  (MIPStarRE.QPBT.pauli_soundness)
/-- `thm:pauli`: every sufficiently successful Pauli basis test strategy admits
local isometries and an auxiliary unit state for which the state and both
raw prescribed-answer operator families are close at scale `deltaQld`. The theorem uses the
once-and-for-all self-dual-normal field model selected by `fixedFieldModel` for
each admissible size, rather than a freshly quantified field identification.
Blueprint
`thm:pauli`; paper origin
`references/qpbt-paper/08_classical_and_quantum_low_degree_tests.tex:1426-1447`.

The paper's asymptotic constants are encoded by the explicit `deltaQld`
functional; the squared operator distances use the quantitative convention of
blueprint `def:povm-distance`.
-/
theorem pauli_soundness :
    ∃ a b : ℝ, 1 ≤ a ∧ 0 < b ∧ b < 1 ∧
      ∀ (P : AdmissibleParams) (ε : ℝ), 0 ≤ ε →
        ∀ S : Strategy (pauliBasisTest P), 1 - ε ≤ S.value →
          ∃ w : PauliSoundnessWitness P S,
            ‖isometryTensor w.φA w.φB S.ψ - idealState P w.aux‖ ≤
                deltaQld a b ε P.m P.d P.q ∧
            (∀ W : PauliKind,
              rawPauliOperatorDistanceA P S w W ≤ deltaQld a b ε P.m P.d P.q) ∧
            (∀ W : PauliKind,
              rawPauliOperatorDistanceB P S w W ≤ deltaQld a b ε P.m P.d P.q) := by
  sorry

-- source: MIPStarRE/QPBT/Test/QubitForm.lean:411-436  (MIPStarRE.QPBT.pauli_soundness_qubit)
/-- `cor:pauli-binary`: soundness of the Pauli basis test in qubit
coordinates. Blueprint `cor:pauli-binary`, paper
`08_classical_and_quantum_low_degree_tests.tex:1450-1491`.

The theorem assumes a nonnegative error parameter, as in the source, and uses
only `P.model` and its stored basis dimension.

**Proof dependency:** The coordinate change and all three error identities are
proved, and the source theorem `pauli_soundness` is proved as well, so this
corollary is complete: its axiom closure is `propext`, `Classical.choice` and
`Quot.sound`. The composition that closed `pauli_soundness` is recorded in
issue #614, under the umbrella issue #529. -/
theorem pauli_soundness_qubit :
    ∃ a b : ℝ, 1 ≤ a ∧ 0 < b ∧ b < 1 ∧
      ∀ (P : AdmissibleParams) (ε : ℝ), 0 ≤ ε →
        ∀ S : Strategy (pauliBasisTest P), 1 - ε ≤ S.value →
          ∃ w : QubitSoundnessWitness P S,
            ‖isometryTensor w.φA w.φB S.ψ - idealQubitState P w.aux‖ ≤
                deltaQld a b ε P.m P.d P.q ∧
            (∀ W : PauliKind,
              qubitOperatorDistanceA P S w W ≤
                deltaQld a b ε P.m P.d P.q) ∧
            ∀ W : PauliKind,
              qubitOperatorDistanceB P S w W ≤
                deltaQld a b ε P.m P.d P.q := by
  sorry

end MIPStarRE.QPBT
