module

public import MIPStarRE.LDT.Basic.DistributionUniform

/-!
# Conditionally linear functions and graph distributions

The question distributions in the Pauli basis test are generated by a finite
graph of types and a shared seed, with each type applying a conditionally linear
map to that seed.  A conditionally linear map of level `ell` is a sum of `ell`
linear contributions on pairwise disjoint register subspaces, each contribution
selected by the values of the preceding ones.  The inductive predicate records
this decomposition, and the graph distribution is the law of the type pair.
Equal-level maps over pairwise disjoint coordinate registers have coordinatewise
direct sums whose shared-seed laws factor as products.

## References

The source-facing nodes are blueprint `def:cl-func`, `def:cl-dist`,
`lem:cl-concat`, and `def:graph-distribution`.
The paper origins are
`references/qpbt-paper/05_conditionally_linear_functions.tex:35-57,282-314`,
`references/qpbt-paper/07_types.tex:65-82`,
and `references/qpbt-paper/08_classical_and_quantum_low_degree_tests.tex:964-1010`.
-/

@[expose] public section

open scoped BigOperators

namespace MIPStarRE.QPBT

open MIPStarRE.LDT

variable {K ι : Type*} [Field K] [Fintype ι] [DecidableEq ι]

/--
The source definition is recursive in the residual map.  A direct inductive
predicate with that recursive occurrence under a dependent finite-set index is
rejected by Lean's strict-positivity checker.  We therefore expose the same
public predicate through a positive syntax tree (`CondLinearTerm`), together
with its support invariant and evaluation function.  This is a representation
deviation forced by Lean, not an additional mathematical hypothesis.  It encodes
blueprint `def:cl-func`,
paper origin `references/qpbt-paper/05_conditionally_linear_functions.tex:35-57`.
-/
inductive CondLinearTerm (K : Type*) [Field K] {ι : Type*} [Fintype ι]
    [DecidableEq ι] : ℕ → Type _ where
  | zero : CondLinearTerm K (ι := ι) 0
  | succ {ell : ℕ}
      (S₁ : Finset ι)
      (L₁ : (ι → K) →ₗ[K] (ι → K))
      (hSupport : ∀ x i, i ∉ S₁ → L₁ x i = 0)
      (rest : (ι → K) → CondLinearTerm K (ι := ι) ell) :
      CondLinearTerm K (ι := ι) (ell + 1)

/-- Restrict a coordinate vector to a register, zeroing the complementary
coordinates.  This is Lean-only support for the projections in blueprint
`def:cl-func`, paper origin
`references/qpbt-paper/05_conditionally_linear_functions.tex:35-57`.
-/
def coordinateRestriction (S : Finset ι) (x : ι → K) : ι → K :=
  fun i => if i ∈ S then x i else 0

/-- Evaluation of a representation of a conditionally linear function.
Lean-only support for blueprint
`def:cl-func`, paper origin
`references/qpbt-paper/05_conditionally_linear_functions.tex:35-57`.
-/
def CondLinearTerm.eval {ι : Type*} [Fintype ι] [DecidableEq ι]
    {K : Type*} [Field K] :
    {ell : ℕ} → CondLinearTerm K (ι := ι) ell → (ι → K) → (ι → K)
  | _, .zero => fun _ => 0
  | _, .succ S₁ L₁ _ rest =>
      fun x =>
        let x₁ := coordinateRestriction S₁ x
        L₁ x₁ + CondLinearTerm.eval (rest (L₁ x₁)) x

/-- The support invariant for a representation of a conditionally linear
function.  This is a Lean-only companion to blueprint
`def:cl-func`, paper origin
`references/qpbt-paper/05_conditionally_linear_functions.tex:35-57`.
-/
def CondLinearTerm.supportedOn {ι : Type*} [Fintype ι] [DecidableEq ι]
    {K : Type*} [Field K] :
    {ell : ℕ} → CondLinearTerm K (ι := ι) ell → Finset ι → Prop
  | _, .zero, _ => True
  | _, .succ S₁ _ _ rest, S =>
      S₁ ⊆ S ∧ ∀ y, CondLinearTerm.supportedOn (rest y) (S \ S₁)

/-- The public conditionally-linear predicate.  Its positive syntax-tree
encoding is the Lean representation of blueprint
`def:cl-func`, paper origin
`references/qpbt-paper/05_conditionally_linear_functions.tex:35-57`.
-/
def IsCondLinearOn (K : Type*) [Field K] {ι : Type*} [Fintype ι]
    [DecidableEq ι] (S : Finset ι) (ell : ℕ)
    (L : (ι → K) → (ι → K)) : Prop :=
  ∃ t : CondLinearTerm K (ι := ι) ell,
    CondLinearTerm.supportedOn t S ∧ CondLinearTerm.eval t = L

/--
`IsCondLinear` abbreviates the full-coordinate predicate.  Blueprint
`def:cl-func`; paper
`references/qpbt-paper/05_conditionally_linear_functions.tex:35-57`.
-/
def IsCondLinear (ell : ℕ) (L : (ι → K) → (ι → K)) : Prop :=
  IsCondLinearOn K Finset.univ ell L

/-- The zero conditionally linear function at every level, used to extend the
family `R u` from the image `L(U)` to all indices in the concatenation
construction of `lem:cl-concat`. -/
private def CondLinearTerm.zeroOfLevel {K ι : Type*} [Field K]
    [Fintype ι] [DecidableEq ι] : (ell : ℕ) → CondLinearTerm K (ι := ι) ell
  | 0 => .zero
  | ell + 1 => .succ ∅ 0 (by simp) (fun _ => zeroOfLevel ell)

@[simp]
private theorem CondLinearTerm.eval_zeroOfLevel {K ι : Type*} [Field K]
    [Fintype ι] [DecidableEq ι] (ell : ℕ) (x : ι → K) :
    CondLinearTerm.eval (CondLinearTerm.zeroOfLevel (K := K) (ι := ι) ell) x = 0 := by
  induction ell with
  | zero => rfl
  | succ ell ih =>
      simp [CondLinearTerm.zeroOfLevel, CondLinearTerm.eval, ih]

private theorem CondLinearTerm.zeroOfLevel_supportedOn {K ι : Type*} [Field K]
    [Fintype ι] [DecidableEq ι] (ell : ℕ) (S : Finset ι) :
    CondLinearTerm.supportedOn
      (CondLinearTerm.zeroOfLevel (K := K) (ι := ι) ell) S := by
  induction ell generalizing S with
  | zero => trivial
  | succ ell ih =>
      exact ⟨by simp, fun _ => ih _⟩

/-- Extending the support set preserves the support invariant. -/
private theorem CondLinearTerm.supportedOn_mono {K ι : Type*} [Field K]
    [Fintype ι] [DecidableEq ι] {ell : ℕ}
    {t : CondLinearTerm K (ι := ι) ell} {S T : Finset ι}
    (ht : CondLinearTerm.supportedOn t S) (hST : S ⊆ T) :
    CondLinearTerm.supportedOn t T := by
  induction t generalizing S T with
  | zero => trivial
  | @succ ell S₁ L₁ hSupport rest ih =>
      rcases ht with ⟨hS₁, hrest⟩
      refine ⟨hS₁.trans hST, fun y => ih y (hrest y) ?_⟩
      exact Finset.sdiff_subset_sdiff hST (fun _ h => h)

/-- Lift a linear map to the left summand of a direct sum of registers. -/
private def condLinearLiftLeft {K ιU ιV : Type*} [Field K]
    (L : (ιU → K) →ₗ[K] (ιU → K)) :
    (ιU ⊕ ιV → K) →ₗ[K] (ιU ⊕ ιV → K) where
  toFun x := Sum.elim (L (fun i => x (.inl i))) 0
  map_add' x y := by
    ext i
    cases i with
    | inl i => exact congrFun (L.map_add _ _) i
    | inr i => simp
  map_smul' c x := by
    ext i
    cases i with
    | inl i => exact congrFun (L.map_smul c _) i
    | inr i => simp

/-- Lift a linear map to the right summand of a direct sum of registers. -/
private def condLinearLiftRight {K ιU ιV : Type*} [Field K]
    (L : (ιV → K) →ₗ[K] (ιV → K)) :
    (ιU ⊕ ιV → K) →ₗ[K] (ιU ⊕ ιV → K) where
  toFun x := Sum.elim 0 (L (fun i => x (.inr i)))
  map_add' x y := by
    ext i
    cases i with
    | inl i => simp
    | inr i => exact congrFun (L.map_add _ _) i
  map_smul' c x := by
    ext i
    cases i with
    | inl i => simp
    | inr i => exact congrFun (L.map_smul c _) i

/-- Lift a representation of a conditionally linear function to the right
summand of a direct sum of registers. -/
private def CondLinearTerm.liftRight {K ιU ιV : Type*} [Field K]
    [Fintype ιU] [DecidableEq ιU] [Fintype ιV] [DecidableEq ιV] :
    {ell : ℕ} → CondLinearTerm K (ι := ιV) ell →
      CondLinearTerm K (ι := ιU ⊕ ιV) ell
  | _, .zero => .zero
  | _, .succ S₁ L₁ hSupport rest =>
      .succ (S₁.map Function.Embedding.inr) (condLinearLiftRight L₁)
        (by
          intro x i hi
          cases i with
          | inl i => rfl
          | inr i =>
              apply hSupport
              simpa using hi)
        (fun y => liftRight (rest (fun i => y (.inr i))))

@[simp]
private theorem CondLinearTerm.eval_liftRight {K ιU ιV : Type*} [Field K]
    [Fintype ιU] [DecidableEq ιU] [Fintype ιV] [DecidableEq ιV]
    {ell : ℕ} (t : CondLinearTerm K (ι := ιV) ell) (x : ιU ⊕ ιV → K) :
    CondLinearTerm.eval (CondLinearTerm.liftRight (ιU := ιU) t) x =
      Sum.elim (0 : ιU → K) (CondLinearTerm.eval t (fun i => x (.inr i))) := by
  induction t with
  | zero =>
      simp [CondLinearTerm.liftRight, CondLinearTerm.eval]
  | @succ ell S₁ L₁ hSupport rest ih =>
      ext i
      cases i <;>
        simp [CondLinearTerm.liftRight, CondLinearTerm.eval, condLinearLiftRight,
          coordinateRestriction, ih]; rfl

private theorem CondLinearTerm.liftRight_supportedOn {K ιU ιV : Type*}
    [Field K] [Fintype ιU] [DecidableEq ιU] [Fintype ιV] [DecidableEq ιV]
    {ell : ℕ} {t : CondLinearTerm K (ι := ιV) ell} {S : Finset ιV}
    (ht : CondLinearTerm.supportedOn t S) :
    CondLinearTerm.supportedOn (CondLinearTerm.liftRight (ιU := ιU) t)
      (S.map Function.Embedding.inr) := by
  induction t generalizing S with
  | zero => trivial
  | @succ ell S₁ L₁ hSupport rest ih =>
      rcases ht with ⟨hS₁, hrest⟩
      refine ⟨Finset.map_subset_map.mpr hS₁, fun y => ?_⟩
      have hsets :
          (S \ S₁).map (Function.Embedding.inr : ιV ↪ ιU ⊕ ιV) =
            S.map Function.Embedding.inr \ S₁.map Function.Embedding.inr := by
        ext i
        cases i <;> simp
      rw [← hsets]
      exact ih (fun i => y (.inr i)) (hrest (fun i => y (.inr i)))

/-- Concatenate a family of conditionally linear representations on the right
register with a conditionally linear representation on the left register, while
recording the prefix accumulated by the preceding left levels. -/
private def CondLinearTerm.concat {K ιU ιV : Type*} [Field K]
    [Fintype ιU] [DecidableEq ιU] [Fintype ιV] [DecidableEq ιV]
    {ell : ℕ} (rTerm : (ιU → K) → CondLinearTerm K (ι := ιV) ell)
    (acc : ιU → K) :
    {k : ℕ} → CondLinearTerm K (ι := ιU) k →
      CondLinearTerm K (ι := ιU ⊕ ιV) (ell + k)
  | _, .zero => CondLinearTerm.liftRight (rTerm acc)
  | _, .succ S₁ L₁ hSupport rest =>
      .succ (S₁.map Function.Embedding.inl) (condLinearLiftLeft L₁)
        (by
          intro x i hi
          cases i with
          | inl i =>
              apply hSupport
              simpa using hi
          | inr i => rfl)
        (fun y => concat rTerm (acc + fun i => y (.inl i))
          (rest (fun i => y (.inl i))))

private theorem CondLinearTerm.eval_concat {K ιU ιV : Type*} [Field K]
    [Fintype ιU] [DecidableEq ιU] [Fintype ιV] [DecidableEq ιV]
    {ell k : ℕ} (rTerm : (ιU → K) → CondLinearTerm K (ι := ιV) ell)
    (acc : ιU → K) (t : CondLinearTerm K (ι := ιU) k)
    (x : ιU ⊕ ιV → K) :
    CondLinearTerm.eval (CondLinearTerm.concat rTerm acc t) x =
      Sum.elim (CondLinearTerm.eval t (fun i => x (.inl i)))
        (CondLinearTerm.eval
          (rTerm (acc + CondLinearTerm.eval t (fun i => x (.inl i))))
          (fun i => x (.inr i))) := by
  induction t generalizing acc with
  | zero =>
      simp [CondLinearTerm.concat, CondLinearTerm.eval]
  | @succ k S₁ L₁ hSupport rest ih =>
      ext i
      cases i <;>
        simp [CondLinearTerm.concat, CondLinearTerm.eval, condLinearLiftLeft,
          coordinateRestriction, ih, add_assoc] <;> rfl

private theorem CondLinearTerm.concat_supportedOn {K ιU ιV : Type*} [Field K]
    [Fintype ιU] [DecidableEq ιU] [Fintype ιV] [DecidableEq ιV]
    {ell k : ℕ} {rTerm : (ιU → K) → CondLinearTerm K (ι := ιV) ell}
    {acc : ιU → K} {t : CondLinearTerm K (ι := ιU) k}
    {SU : Finset ιU} {SV : Finset ιV}
    (ht : CondLinearTerm.supportedOn t SU)
    (hr : ∀ u, CondLinearTerm.supportedOn (rTerm u) SV) :
    CondLinearTerm.supportedOn (CondLinearTerm.concat rTerm acc t)
      (SU.map Function.Embedding.inl ∪ SV.map Function.Embedding.inr) := by
  induction t generalizing acc SU with
  | zero =>
      exact CondLinearTerm.supportedOn_mono
        (CondLinearTerm.liftRight_supportedOn (hr acc)) Finset.subset_union_right
  | @succ k S₁ L₁ hSupport rest ih =>
      rcases ht with ⟨hS₁, hrest⟩
      refine ⟨(Finset.map_subset_map.mpr hS₁).trans Finset.subset_union_left,
        fun y => ?_⟩
      have hrec := ih (fun i => y (.inl i)) (acc := acc + fun i => y (.inl i))
        (hrest (fun i => y (.inl i)))
      have hsets :
          (SU \ S₁).map Function.Embedding.inl ∪ SV.map Function.Embedding.inr =
            (SU.map Function.Embedding.inl ∪ SV.map Function.Embedding.inr) \
              S₁.map Function.Embedding.inl := by
        ext i
        cases i <;> simp
      simpa only [hsets] using hrec

/--
The distribution obtained by applying two conditionally linear maps to a common
uniform seed.  This is blueprint
`def:cl-dist`, paper origin
`references/qpbt-paper/05_conditionally_linear_functions.tex:132-138`.
-/
noncomputable def clDistribution [Fintype K] [DecidableEq K]
    (L R : (ι → K) → (ι → K)) :
    Distribution ((ι → K) × (ι → K)) :=
  (uniformDistribution (ι → K)).map (fun z => (L z, R z))

/-- The direct-sum map used to encode the paper's CL concatenation.  The left
coordinates carry `L`, while the right coordinates carry the family member
`R u v` selected by the left input `u`.  This is Lean-only coordinate
infrastructure for blueprint
`lem:cl-concat`, paper origin
`references/qpbt-paper/05_conditionally_linear_functions.tex:282-314`.
-/
def condLinearConcat {ιU ιV : Type*} [Fintype ιU] [DecidableEq ιU]
    [Fintype ιV] [DecidableEq ιV] (L : (ιU → K) → (ιU → K))
    (R : (ιU → K) → (ιV → K) → (ιV → K))
    (x : ιU ⊕ ιV → K) : ιU ⊕ ιV → K :=
  let u : ιU → K := fun i => x (.inl i)
  let v : ιV → K := fun j => x (.inr j)
  Sum.elim (L u) (R (L u) v)

/--
Concatenating an outer and an indexed inner CL map adds their levels.  This is
blueprint `lem:cl-concat`, with
paper origin `references/qpbt-paper/05_conditionally_linear_functions.tex:282-292`.
The map `condLinearConcat` realizes this concatenation on the direct sum.
-/
theorem IsCondLinearOn.concat {ιU ιV : Type*} [Fintype ιU] [DecidableEq ιU]
    [Fintype ιV] [DecidableEq ιV] {ell k : ℕ}
    {L : (ιU → K) → (ιU → K)}
    {R : (ιU → K) → (ιV → K) → (ιV → K)}
    (hL : IsCondLinearOn K (Finset.univ : Finset ιU) k L)
    (hR : ∀ u : ιU → K, u ∈ Set.range L →
      IsCondLinearOn K (Finset.univ : Finset ιV) ell (R u)) :
    IsCondLinearOn K (Finset.univ : Finset (ιU ⊕ ιV)) (k + ell)
      (condLinearConcat L R) := by
  classical
  rcases hL with ⟨tL, htL, htL_eval⟩
  let rTerm : (ιU → K) → CondLinearTerm K (ι := ιV) ell := fun u =>
    if hu : u ∈ Set.range L then Classical.choose (hR u hu)
    else CondLinearTerm.zeroOfLevel ell
  have hr_supported (u : ιU → K) :
      CondLinearTerm.supportedOn (rTerm u) (Finset.univ : Finset ιV) := by
    by_cases hu : u ∈ Set.range L
    · simp only [rTerm, dif_pos hu]
      exact (Classical.choose_spec (hR u hu)).1
    · simp only [rTerm, dif_neg hu]
      exact CondLinearTerm.zeroOfLevel_supportedOn ell Finset.univ
  have hr_eval (u : ιU → K) (hu : u ∈ Set.range L) :
      CondLinearTerm.eval (rTerm u) = R u := by
    simp only [rTerm, dif_pos hu]
    exact (Classical.choose_spec (hR u hu)).2
  rw [Nat.add_comm k ell]
  refine ⟨CondLinearTerm.concat rTerm 0 tL, ?_, ?_⟩
  · have hsupport := CondLinearTerm.concat_supportedOn
      (acc := (0 : ιU → K)) htL hr_supported
    have huniv :
        (Finset.univ : Finset ιU).map Function.Embedding.inl ∪
            (Finset.univ : Finset ιV).map Function.Embedding.inr =
          (Finset.univ : Finset (ιU ⊕ ιV)) := by
      ext i
      cases i <;> simp
    simpa only [huniv] using hsupport
  · funext x
    rw [CondLinearTerm.eval_concat]
    simp only [zero_add]
    rw [congrFun htL_eval (fun i => x (.inl i))]
    rw [hr_eval (L (fun i => x (.inl i))) ⟨_, rfl⟩]
    rfl

/--
The graph distribution is uniform on ordered pairs `(a, b)` whose unordered
pair belongs to `E`, including self-loops.  This is blueprint
`def:graph-distribution`;
paper origin `references/qpbt-paper/08_classical_and_quantum_low_degree_tests.tex:984-1009`.
The underlying graph-distribution definition is
`references/qpbt-paper/07_types.tex:65-82`.
-/
noncomputable def graphDistribution {T : Type*} [Fintype T] [DecidableEq T]
    (E : Finset (Sym2 T)) (_hE : E.Nonempty) : Distribution (T × T) :=
  Distribution.uniformOnFinset
    (Finset.univ.filter fun ab : T × T => Sym2.mk ab.1 ab.2 ∈ E)

/-- The graph distribution has total mass one whenever its edge set is
nonempty.  This is not a named statement of the source article; it is
blueprint
`lem:graph-distribution-mass`. -/
theorem graphDistribution_isProbability {T : Type*} [Fintype T] [DecidableEq T]
    (E : Finset (Sym2 T)) (hE : E.Nonempty) :
    (graphDistribution E hE).IsProbability := by
  apply Distribution.uniformOnFinset_isProbability
  obtain ⟨e, he⟩ := hE
  obtain ⟨⟨a, b⟩, rfl⟩ := Sym2.mk_surjective e
  change s(a, b) ∈ E at he
  exact ⟨(a, b), Finset.mem_filter.mpr ⟨Finset.mem_univ _, he⟩⟩

/-- The graph distribution is symmetric in its two arguments: it is uniform on
the ordered pairs whose unordered pair is an edge, and that condition does not
depend on the order of the pair.  This is not a named statement of the source
article; it is `lem:graph-distribution-symm` in
`blueprint/src/chapter/ch12_qpbt_games.tex`. -/
theorem graphDistribution_symm {T : Type*} [Fintype T] [DecidableEq T]
    (E : Finset (Sym2 T)) (hE : E.Nonempty) (a b : T) :
    (graphDistribution E hE).weight (a, b) =
      (graphDistribution E hE).weight (b, a) := by
  classical
  simp [graphDistribution, Distribution.uniformOnFinset_weight, Sym2.eq_swap]

end MIPStarRE.QPBT
